// Unit test for the MP4 container parser. No Qt, no library - see src/container/Mp4Parser.h.
//
// The expectations are ground truth taken from an ffmpeg-written AV1-in-MP4 file before the parser
// existed, by dumping the boxes with an independent script: 25 samples whose sizes sum to 18551,
// which is exactly the mdat payload, one chunk starting at the mdat payload offset, sync samples
// 1/11/21 for -g 10, and a 13 byte av1C configOBU blob. If the parser agrees with all of those it
// is reading the same file the rest of the world does.
//
// The file is generated by tests/run-regression.sh and arrives in BDA_TEST_MP4 (or argv[1] when
// run by hand); without it the test skips rather than inventing a fixture, because a hand-built
// MP4 would only prove the parser agrees with my own idea of the format.
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <numeric>
#include <string>
#include <vector>

#include "container/Mp4Parser.h"
#include "container/Mp4SampleTable.h"

namespace
{
int  g_failures = 0;
void check(bool ok, const std::string &what)
{
  std::cout << (ok ? "  ok    " : "  FAIL  ") << what << std::endl;
  if (!ok)
    ++g_failures;
}

template <typename T> void checkEqual(T got, T want, const std::string &what)
{
  const bool ok = got == want;
  std::cout << (ok ? "  ok    " : "  FAIL  ") << what;
  if (!ok)
    std::cout << "  (got " << got << ", want " << want << ")";
  std::cout << std::endl;
  if (!ok)
    ++g_failures;
}

std::vector<std::uint8_t> readFile(const std::string &path)
{
  std::ifstream stream(path, std::ios::binary);
  if (!stream)
    return {};
  return std::vector<std::uint8_t>(std::istreambuf_iterator<char>(stream),
                                   std::istreambuf_iterator<char>());
}

using namespace bda::container;
} // namespace

int main(int argc, char **argv)
{
  std::cout << "mp4 container parser" << std::endl;

  // --- degenerate input, which needs no fixture -------------------------------------------
  {
    const auto empty = parseMp4Boxes(nullptr, 0);
    check(!empty.ok(), "a null buffer is rejected");
    const std::uint8_t stub[4]{0, 0, 0, 8};
    const auto         tooShort = parseMp4Boxes(stub, sizeof(stub));
    check(!tooShort.ok(), "a buffer shorter than one header is rejected");
  }
  {
    check(isMp4ContainerBox("moov"), "moov is a container");
    check(isMp4ContainerBox("stbl"), "stbl is a container");
    check(isMp4ContainerBox("stsd"), "stsd is walked as a container");
    /* The important negative. mdat holds coded video; descending into it would parse sample bytes
     * as box headers and produce a convincing tree of nonsense.
     */
    check(!isMp4ContainerBox("mdat"), "mdat is NOT a container");
    check(!isMp4ContainerBox("ftyp"), "ftyp is not a container");
  }

  /* The regression runner compiles unit tests with source arguments only, so the file arrives by
   * environment there and by argv when run by hand.
   */
  std::string path = argc >= 2 ? argv[1] : "";
  if (path.empty())
    if (const char *fromEnv = std::getenv("BDA_TEST_MP4"))
      path = fromEnv;

  if (path.empty())
  {
    std::cout << "SKIP (no mp4 given; pass one as argv[1] or set BDA_TEST_MP4)" << std::endl;
    return g_failures == 0 ? 0 : 1;
  }

  const auto file = readFile(path);
  if (file.empty())
  {
    std::cout << "SKIP (could not read " << path << ")" << std::endl;
    return g_failures == 0 ? 0 : 1;
  }
  std::cout << "  file: " << path << " (" << file.size() << " bytes)" << std::endl;

  // --- the box tree -----------------------------------------------------------------------
  const auto parsed = parseMp4Boxes(file.data(), file.size());
  check(parsed.ok(), "a well formed file parses without error");
  if (!parsed.ok())
    std::cout << "        error: " << parsed.error << std::endl;
  check(!parsed.truncated, "and is not reported truncated");

  check(!parsed.boxes.empty() && parsed.boxes.front().type == "ftyp",
        "the first top level box is ftyp");
  {
    bool haveMoov = false, haveMdat = false;
    for (const auto &box : parsed.boxes)
    {
      haveMoov = haveMoov || box.type == "moov";
      haveMdat = haveMdat || box.type == "mdat";
    }
    check(haveMoov && haveMdat, "moov and mdat are both at the top level");
  }
  {
    const auto *mdat = findMp4Box(parsed.boxes, "mdat");
    check(mdat != nullptr && mdat->children.empty(), "mdat is a leaf, not a tree of sample bytes");
  }

  // --- the path a sample table lives at ---------------------------------------------------
  const auto *stbl = findMp4Box(parsed.boxes, "moov/trak/mdia/minf/stbl");
  check(stbl != nullptr, "the sample table is found at moov/trak/mdia/minf/stbl");
  check(findMp4Box(parsed.boxes, "moov/trak/mdia/minf/stbl/stsz") != nullptr, "stsz is present");
  check(findMp4Box(parsed.boxes, "moov/nope/stbl") == nullptr, "a wrong path finds nothing");

  // --- the stsd rule, which the generic walk cannot get right -----------------------------
  {
    const auto *stsd = findMp4Box(parsed.boxes, "moov/trak/mdia/minf/stbl/stsd");
    check(stsd != nullptr && !stsd->children.empty(), "stsd holds a sample entry");
    if (stsd != nullptr && !stsd->children.empty())
    {
      const auto &entry = stsd->children.front();
      checkEqual(entry.type, std::string("av01"), "the sample entry is av01");
      /* av1C sits after the 78 fixed bytes of a VisualSampleEntry. Parsing the entry payload from
       * its start instead reads those fields as a box header and finds nothing.
       */
      check(!findMp4Children(entry, "av1C").empty(), "av1C is found inside the sample entry");
    }
  }

  // --- tracks and located samples ---------------------------------------------------------
  const auto tracks = readMp4Tracks(file.data(), file.size(), parsed);
  checkEqual(tracks.size(), std::size_t(1), "the file has one track");
  if (!tracks.empty())
  {
    const auto &track = tracks.front();
    if (!track.error.empty())
      std::cout << "        track error: " << track.error << std::endl;
    check(track.error.empty(), "the track reads without error");
    check(track.isAv1(), "the track is AV1");
    checkEqual(track.handlerType, std::string("vide"), "the handler is vide");
    checkEqual(track.width, 176, "width comes from the sample entry");
    checkEqual(track.height, 144, "height comes from the sample entry");
    checkEqual(track.id, std::uint32_t(1), "the track id is read from tkhd");

    checkEqual(track.samples.size(), std::size_t(25), "25 samples are located");

    /* The whole point of the sample table: every sample must land inside mdat's payload and the
     * sizes must account for all of it. This is the check that would catch an off-by-one in the
     * stsc walk, which is otherwise invisible - the offsets would still look reasonable.
     */
    const auto *mdat = findMp4Box(parsed.boxes, "mdat");
    check(mdat != nullptr, "mdat is present for the containment check");
    if (mdat != nullptr && !track.samples.empty())
    {
      const auto payloadBegin = mdat->payloadOffset();
      const auto payloadEnd   = mdat->offset + mdat->size;

      checkEqual(track.samples.front().offset, payloadBegin,
                 "the first sample starts at the mdat payload");

      bool contained = true;
      for (const auto &sample : track.samples)
        contained = contained && sample.offset >= payloadBegin &&
                    sample.offset + sample.size <= payloadEnd;
      check(contained, "every sample lies inside mdat");

      const auto total = std::accumulate(
          track.samples.begin(), track.samples.end(), std::uint64_t(0),
          [](std::uint64_t sum, const Mp4Sample &sample) { return sum + sample.size; });
      checkEqual(total, mdat->payloadSize(), "the sample sizes account for all of mdat");

      bool consecutive = true;
      for (std::size_t index = 1; index < track.samples.size(); ++index)
        consecutive = consecutive && track.samples[index].offset ==
                                         track.samples[index - 1].offset +
                                             track.samples[index - 1].size;
      check(consecutive, "samples in one chunk are laid out back to back");
    }

    // -g 10 over 25 frames: key frames at 1, 11 and 21, which stss records 1-based.
    {
      std::vector<std::size_t> syncs;
      for (std::size_t index = 0; index < track.samples.size(); ++index)
        if (track.samples[index].sync)
          syncs.push_back(index);
      checkEqual(syncs.size(), std::size_t(3), "three sync samples");
      if (syncs.size() == 3)
        check(syncs[0] == 0 && syncs[1] == 10 && syncs[2] == 20,
              "and they are samples 1, 11, 21 (1-based)");
    }

    // stts is one run of 25 at a constant delta, so decode times must be strictly increasing.
    {
      bool increasing = true;
      for (std::size_t index = 1; index < track.samples.size(); ++index)
        increasing = increasing && track.samples[index].decodeTime >
                                       track.samples[index - 1].decodeTime;
      check(increasing, "decode times increase with sample order");
      check(track.samples.front().decodeTime == 0, "and start at zero");
    }

    // The config OBUs are not in any sample; without them the first frame has no sequence header.
    checkEqual(track.av1ConfigObus.size(), std::size_t(13), "av1C carries 13 bytes of config OBUs");
    if (!track.av1ConfigObus.empty())
      check(track.av1ConfigObus.front() == 0x0a,
            "the first config OBU is a sequence header with a size field (0x0a)");
  }

  // --- truncation, derived from the real file rather than invented -------------------------
  {
    /* Cutting the file mid-mdat is what a capture interrupted by a crash looks like. The parser
     * must say so and still hand back the boxes it did read - the moov is intact and is the most
     * useful thing on screen at that point.
     */
    auto cut = file;
    cut.resize(file.size() - 64);
    const auto reparsed = parseMp4Boxes(cut.data(), cut.size());
    check(!reparsed.ok(), "a truncated file is reported as an error");
    check(reparsed.truncated, "and specifically as truncated");
    check(findMp4Box(reparsed.boxes, "moov/trak/mdia/minf/stbl") != nullptr,
          "while the boxes before the cut are still returned");

    const auto cutTracks = readMp4Tracks(cut.data(), cut.size(), reparsed);
    check(!cutTracks.empty() && !cutTracks.front().error.empty(),
          "and the track reports that a sample runs past the end of the file");
  }

  std::cout << (g_failures == 0 ? "PASS" : "FAIL") << " (" << g_failures << " failures)"
            << std::endl;
  return g_failures == 0 ? 0 : 1;
}
